### ISSUE TITLE
children are never added to a person

### ISSUE THREAD

**Issue by matteobart** [matteobart/gedcom-reader#19]
Currently a family can have children, but I don't think those children ever get added to the person's children list. I see some functions assume that this happens ... it doesn't. So either change your assumption and use the familys instead or add it to the process in the ged_parser.

**Comment by matteobart** [comment]
omg its a user story (US26), I guess this is mine then

**Comment by codankra** [comment]
good job!!!!!! :+1: :1st_place_medal: :100:
