### ISSUE TITLE
Refactor: Date storage

### ISSUE THREAD

**Issue by codankra** [matteobart/gedcom-reader#4]
Birthdays, Marriage/Divorce dates should not have timestamps, should be in a unified format that includes the month, day and year

**Comment by codankra** [comment]
(Is issue because) people aren't married or divorced exactly at midnight automatically

**Comment by matteobart** [comment]
hmmm when we switch to mongodb, mongo stores them as datetime objects rather than date objects

by switching to simply date will be more of a hassle when we add mongo integration
